name: Test Upload Artifact

on: [push]

jobs:
  test-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload test file
        uses: actions/upload-artifact@v2.3.1
        with:
          name: test-artifact
          path: README.md
