name: Build macOS App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"  # 根据需要选择 Python 版本

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          # 根据需要安装打包工具，这里示例使用 PyInstaller
          pip install pyinstaller

      - name: Build .app using PyInstaller
        run: |
          # 请将 unzip_win.py 替换为你的实际入口脚本文件名
          pyinstaller --windowed --onefile unzip_win.py
          # 如果使用 py2app，则可更改为：
          # pip install py2app
          # python setup.py py2app

      - name: Upload Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: macos-build
          path: dist/  # 根据实际生成目录进行调整
