name: Test Upload Artifact

on: [push]

jobs:
  test-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Upload artifact test
        uses: actions/upload-artifact@v2.3.1
        with:
          name: test-file
          path: README.md
